// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package group

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-ionoscloud.group.Group",
		reflect.TypeOf((*Group)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accessActivityLog", GoGetter: "AccessActivityLog"},
			_jsii_.MemberProperty{JsiiProperty: "accessActivityLogInput", GoGetter: "AccessActivityLogInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageAiModelHub", GoGetter: "AccessAndManageAiModelHub"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageAiModelHubInput", GoGetter: "AccessAndManageAiModelHubInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageApiGateway", GoGetter: "AccessAndManageApiGateway"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageApiGatewayInput", GoGetter: "AccessAndManageApiGatewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageCdn", GoGetter: "AccessAndManageCdn"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageCdnInput", GoGetter: "AccessAndManageCdnInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageCertificates", GoGetter: "AccessAndManageCertificates"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageCertificatesInput", GoGetter: "AccessAndManageCertificatesInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageDns", GoGetter: "AccessAndManageDns"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageDnsInput", GoGetter: "AccessAndManageDnsInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageIamResources", GoGetter: "AccessAndManageIamResources"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageIamResourcesInput", GoGetter: "AccessAndManageIamResourcesInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageKaas", GoGetter: "AccessAndManageKaas"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageKaasInput", GoGetter: "AccessAndManageKaasInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageLogging", GoGetter: "AccessAndManageLogging"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageLoggingInput", GoGetter: "AccessAndManageLoggingInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageMonitoring", GoGetter: "AccessAndManageMonitoring"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageMonitoringInput", GoGetter: "AccessAndManageMonitoringInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageNetworkFileStorage", GoGetter: "AccessAndManageNetworkFileStorage"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageNetworkFileStorageInput", GoGetter: "AccessAndManageNetworkFileStorageInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageVpn", GoGetter: "AccessAndManageVpn"},
			_jsii_.MemberProperty{JsiiProperty: "accessAndManageVpnInput", GoGetter: "AccessAndManageVpnInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "createBackupUnit", GoGetter: "CreateBackupUnit"},
			_jsii_.MemberProperty{JsiiProperty: "createBackupUnitInput", GoGetter: "CreateBackupUnitInput"},
			_jsii_.MemberProperty{JsiiProperty: "createDatacenter", GoGetter: "CreateDatacenter"},
			_jsii_.MemberProperty{JsiiProperty: "createDatacenterInput", GoGetter: "CreateDatacenterInput"},
			_jsii_.MemberProperty{JsiiProperty: "createFlowLog", GoGetter: "CreateFlowLog"},
			_jsii_.MemberProperty{JsiiProperty: "createFlowLogInput", GoGetter: "CreateFlowLogInput"},
			_jsii_.MemberProperty{JsiiProperty: "createInternetAccess", GoGetter: "CreateInternetAccess"},
			_jsii_.MemberProperty{JsiiProperty: "createInternetAccessInput", GoGetter: "CreateInternetAccessInput"},
			_jsii_.MemberProperty{JsiiProperty: "createK8SCluster", GoGetter: "CreateK8SCluster"},
			_jsii_.MemberProperty{JsiiProperty: "createK8SClusterInput", GoGetter: "CreateK8SClusterInput"},
			_jsii_.MemberProperty{JsiiProperty: "createNetworkSecurityGroups", GoGetter: "CreateNetworkSecurityGroups"},
			_jsii_.MemberProperty{JsiiProperty: "createNetworkSecurityGroupsInput", GoGetter: "CreateNetworkSecurityGroupsInput"},
			_jsii_.MemberProperty{JsiiProperty: "createPcc", GoGetter: "CreatePcc"},
			_jsii_.MemberProperty{JsiiProperty: "createPccInput", GoGetter: "CreatePccInput"},
			_jsii_.MemberProperty{JsiiProperty: "createSnapshot", GoGetter: "CreateSnapshot"},
			_jsii_.MemberProperty{JsiiProperty: "createSnapshotInput", GoGetter: "CreateSnapshotInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "manageDataplatform", GoGetter: "ManageDataplatform"},
			_jsii_.MemberProperty{JsiiProperty: "manageDataplatformInput", GoGetter: "ManageDataplatformInput"},
			_jsii_.MemberProperty{JsiiProperty: "manageDbaas", GoGetter: "ManageDbaas"},
			_jsii_.MemberProperty{JsiiProperty: "manageDbaasInput", GoGetter: "ManageDbaasInput"},
			_jsii_.MemberProperty{JsiiProperty: "manageRegistry", GoGetter: "ManageRegistry"},
			_jsii_.MemberProperty{JsiiProperty: "manageRegistryInput", GoGetter: "ManageRegistryInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "reserveIp", GoGetter: "ReserveIp"},
			_jsii_.MemberProperty{JsiiProperty: "reserveIpInput", GoGetter: "ReserveIpInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessActivityLog", GoMethod: "ResetAccessActivityLog"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageAiModelHub", GoMethod: "ResetAccessAndManageAiModelHub"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageApiGateway", GoMethod: "ResetAccessAndManageApiGateway"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageCdn", GoMethod: "ResetAccessAndManageCdn"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageCertificates", GoMethod: "ResetAccessAndManageCertificates"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageDns", GoMethod: "ResetAccessAndManageDns"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageIamResources", GoMethod: "ResetAccessAndManageIamResources"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageKaas", GoMethod: "ResetAccessAndManageKaas"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageLogging", GoMethod: "ResetAccessAndManageLogging"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageMonitoring", GoMethod: "ResetAccessAndManageMonitoring"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageNetworkFileStorage", GoMethod: "ResetAccessAndManageNetworkFileStorage"},
			_jsii_.MemberMethod{JsiiMethod: "resetAccessAndManageVpn", GoMethod: "ResetAccessAndManageVpn"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateBackupUnit", GoMethod: "ResetCreateBackupUnit"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateDatacenter", GoMethod: "ResetCreateDatacenter"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateFlowLog", GoMethod: "ResetCreateFlowLog"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateInternetAccess", GoMethod: "ResetCreateInternetAccess"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateK8SCluster", GoMethod: "ResetCreateK8SCluster"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateNetworkSecurityGroups", GoMethod: "ResetCreateNetworkSecurityGroups"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreatePcc", GoMethod: "ResetCreatePcc"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreateSnapshot", GoMethod: "ResetCreateSnapshot"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetManageDataplatform", GoMethod: "ResetManageDataplatform"},
			_jsii_.MemberMethod{JsiiMethod: "resetManageDbaas", GoMethod: "ResetManageDbaas"},
			_jsii_.MemberMethod{JsiiMethod: "resetManageRegistry", GoMethod: "ResetManageRegistry"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetReserveIp", GoMethod: "ResetReserveIp"},
			_jsii_.MemberMethod{JsiiMethod: "resetS3Privilege", GoMethod: "ResetS3Privilege"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserId", GoMethod: "ResetUserId"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserIds", GoMethod: "ResetUserIds"},
			_jsii_.MemberProperty{JsiiProperty: "s3Privilege", GoGetter: "S3Privilege"},
			_jsii_.MemberProperty{JsiiProperty: "s3PrivilegeInput", GoGetter: "S3PrivilegeInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "userId", GoGetter: "UserId"},
			_jsii_.MemberProperty{JsiiProperty: "userIdInput", GoGetter: "UserIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "userIds", GoGetter: "UserIds"},
			_jsii_.MemberProperty{JsiiProperty: "userIdsInput", GoGetter: "UserIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "users", GoGetter: "Users"},
		},
		func() interface{} {
			j := jsiiProxy_Group{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-ionoscloud.group.GroupConfig",
		reflect.TypeOf((*GroupConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-ionoscloud.group.GroupTimeouts",
		reflect.TypeOf((*GroupTimeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-ionoscloud.group.GroupTimeoutsOutputReference",
		reflect.TypeOf((*GroupTimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "default", GoGetter: "Default"},
			_jsii_.MemberProperty{JsiiProperty: "defaultInput", GoGetter: "DefaultInput"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDefault", GoMethod: "ResetDefault"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resetUpdate", GoMethod: "ResetUpdate"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "update", GoGetter: "Update"},
			_jsii_.MemberProperty{JsiiProperty: "updateInput", GoGetter: "UpdateInput"},
		},
		func() interface{} {
			j := jsiiProxy_GroupTimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-ionoscloud.group.GroupUsers",
		reflect.TypeOf((*GroupUsers)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-ionoscloud.group.GroupUsersList",
		reflect.TypeOf((*GroupUsersList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_GroupUsersList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-ionoscloud.group.GroupUsersOutputReference",
		reflect.TypeOf((*GroupUsersOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "administrator", GoGetter: "Administrator"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "email", GoGetter: "Email"},
			_jsii_.MemberProperty{JsiiProperty: "firstName", GoGetter: "FirstName"},
			_jsii_.MemberProperty{JsiiProperty: "forceSecAuth", GoGetter: "ForceSecAuth"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lastName", GoGetter: "LastName"},
			_jsii_.MemberProperty{JsiiProperty: "password", GoGetter: "Password"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_GroupUsersOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
